name: Build

on: [push,pull_request]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-8.0 ]
        rdbms: [ MySQLv5.6, MySQLv5.7, MariaDBv10.1, MariaDBv10.2, MariaDBv10.3 ]
    name: ${{ matrix.smalltalk }} + ${{ matrix.rdbms }}
    steps:
      - uses: actions/checkout@v2
      - name: Start RDBMS
        run: ./scripts/setup-RDBMS.sh
        env:
          RDBMS: ${{ matrix.rdbms }}
      - name: Set up Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RDBMS: ${{ matrix.rdbms }}
        timeout-minutes: 15
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{matrix.os}}-${{matrix.smalltalk}}-${{ matrix.rdbms }}
          token: ${{ secrets.CODECOV_TOKEN }}
